//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertConfiguration
    {
        public AlertConfiguration()
        {
            this.Notification = new HashSet<Notification>();
            this.Parameter = new HashSet<Parameter>();
        }
    
        public long pkid { get; set; }
        public string state { get; set; }
        public string category { get; set; }
        public long tenantid { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<Parameter> Parameter { get; set; }
    }
}
