//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetUser_Role
    {
        public long pkid { get; set; }
        public long userid { get; set; }
        public long roleid { get; set; }
    
        public virtual FleetUser FleetUser { get; set; }
        public virtual Role Role { get; set; }
    }
}
