//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetManageToolDBContext : DbContext
    {
        public FleetManageToolDBContext()
            : base("name=FleetManageToolDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrator> Administrator { get; set; }
        public DbSet<Alert> Alert { get; set; }
        public DbSet<AlertConfiguration> AlertConfiguration { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Diagnostic> Diagnostic { get; set; }
        public DbSet<DomainSetting> DomainSetting { get; set; }
        public DbSet<DTC> DTC { get; set; }
        public DbSet<FleetUser> FleetUser { get; set; }
        public DbSet<FleetUser_Role> FleetUser_Role { get; set; }
        public DbSet<Geofence> Geofence { get; set; }
        public DbSet<Geofence_Vehicle> Geofence_Vehicle { get; set; }
        public DbSet<HW_Model> HW_Model { get; set; }
        public DbSet<Logo> Logo { get; set; }
        public DbSet<MMY> MMY { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<Obu> Obu { get; set; }
        public DbSet<Obu_Check> Obu_Check { get; set; }
        public DbSet<Operate_Log> Operate_Log { get; set; }
        public DbSet<Parameter> Parameter { get; set; }
        public DbSet<RevisionRecord> RevisionRecord { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SystemSetting> SystemSetting { get; set; }
        public DbSet<Tenant> Tenant { get; set; }
        public DbSet<Trip> Trip { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<Vehicle_AlertConfiguration> Vehicle_AlertConfiguration { get; set; }
        public DbSet<Vehicle_Obu> Vehicle_Obu { get; set; }
        public DbSet<VehicleGroup> VehicleGroup { get; set; }
        public DbSet<VehicleGroup_Vehicle> VehicleGroup_Vehicle { get; set; }
    }
}
