//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMY
    {
        public long pkid { get; set; }
        public string language { get; set; }
        public string mmyMake { get; set; }
        public string mmyModel { get; set; }
        public string mmyYear { get; set; }
        public long mmyIndex { get; set; }
    }
}
