//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obu
    {
        public Obu()
        {
            this.Customer = new HashSet<Customer>();
            this.Vehicle_Obu = new HashSet<Vehicle_Obu>();
        }
    
        public long pkid { get; set; }
        public long tenantid { get; set; }
        public string id { get; set; }
        public string idtype { get; set; }
        public string regkey { get; set; }
        public string status { get; set; }
        public string guid { get; set; }
        public string deviceType { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Vehicle_Obu> Vehicle_Obu { get; set; }
    }
}
