//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obu_Check
    {
        public long pkid { get; set; }
        public string byteid { get; set; }
        public string labelid { get; set; }
        public string mdakey { get; set; }
        public string mdspc { get; set; }
        public string mdots { get; set; }
        public string mdmsn { get; set; }
        public string mdtadm { get; set; }
        public string regkey { get; set; }
        public string authtoken { get; set; }
        public string hwmodel { get; set; }
        public string iccid { get; set; }
        public System.DateTime createdate { get; set; }
        public int status { get; set; }
    }
}
