//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.AlertConfiguration = new HashSet<AlertConfiguration>();
            this.Customer = new HashSet<Customer>();
            this.FleetUser = new HashSet<FleetUser>();
            this.Geofence = new HashSet<Geofence>();
            this.Obu = new HashSet<Obu>();
            this.Operate_Log = new HashSet<Operate_Log>();
            this.SystemSetting = new HashSet<SystemSetting>();
            this.Vehicle = new HashSet<Vehicle>();
            this.VehicleGroup = new HashSet<VehicleGroup>();
        }
    
        public long pkid { get; set; }
        public string companyname { get; set; }
        public string companyid { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string introduction { get; set; }
        public string status { get; set; }
        public string guid { get; set; }
    
        public virtual ICollection<AlertConfiguration> AlertConfiguration { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<FleetUser> FleetUser { get; set; }
        public virtual ICollection<Geofence> Geofence { get; set; }
        public virtual ICollection<Obu> Obu { get; set; }
        public virtual ICollection<Operate_Log> Operate_Log { get; set; }
        public virtual ICollection<SystemSetting> SystemSetting { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
        public virtual ICollection<VehicleGroup> VehicleGroup { get; set; }
    }
}
