//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public long pkid { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<double> startlocationLng { get; set; }
        public Nullable<double> startlocationLat { get; set; }
        public Nullable<double> endlocationLng { get; set; }
        public Nullable<double> endlocationLat { get; set; }
        public Nullable<double> distance { get; set; }
        public long vehicleId { get; set; }
        public Nullable<double> IdleTime { get; set; }
        public string guid { get; set; }
        public string startlocation { get; set; }
        public string endlocation { get; set; }
        public Nullable<int> isFirstFlag { get; set; }
        public Nullable<int> isLastFlag { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
