//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManageToolWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Alert = new HashSet<Alert>();
            this.Geofence_Vehicle = new HashSet<Geofence_Vehicle>();
            this.Trip = new HashSet<Trip>();
            this.Vehicle_AlertConfiguration = new HashSet<Vehicle_AlertConfiguration>();
            this.Vehicle_Obu = new HashSet<Vehicle_Obu>();
            this.VehicleGroup_Vehicle = new HashSet<VehicleGroup_Vehicle>();
        }
    
        public long pkid { get; set; }
        public long tenantid { get; set; }
        public Nullable<long> logoid { get; set; }
        public string id { get; set; }
        public string vin { get; set; }
        public string name { get; set; }
        public string info { get; set; }
        public string licence { get; set; }
        public string drivername { get; set; }
        public Nullable<int> isVinEditable { get; set; }
        public Nullable<int> isMMYEditable { get; set; }
        public string year { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<long> customerid { get; set; }
        public Nullable<long> mmyid { get; set; }
        public string telephone { get; set; }
        public string lable { get; set; }
    
        public virtual ICollection<Alert> Alert { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Geofence_Vehicle> Geofence_Vehicle { get; set; }
        public virtual Logo Logo { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Trip> Trip { get; set; }
        public virtual ICollection<Vehicle_AlertConfiguration> Vehicle_AlertConfiguration { get; set; }
        public virtual ICollection<Vehicle_Obu> Vehicle_Obu { get; set; }
        public virtual ICollection<VehicleGroup_Vehicle> VehicleGroup_Vehicle { get; set; }
    }
}
